# Largely cribbed from Homebrew's homebrew/core tap tests from:
# https://github.com/Homebrew/homebrew-core/blob/201dbb92e491064e0aa8a0942e0ca9c3053158a2/.github/workflows/tests.yml#L34

name: Homebrew Tap Tests

on:
  push:
  pull_request:
  merge_group:

permissions:
  # actions helpers do the checkout
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_ENV_HINTS: 1
  HOMEBREW_BOOTSNAP: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_VERIFY_ATTESTATIONS: 1

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: "${{ github.ref }}"
  # yield to latest change, cancel jobs in progress
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Cache Bundler RubyGems
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-syntax-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-syntax-

      - name: Install Bundler RubyGems
        run: brew install-bundler-gems --groups=style,typecheck

      - name: Install shellcheck and shfmt
        run: brew install shellcheck shfmt

      - name: Cache style cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/Homebrew/style
          key: syntax-style-cache-${{ github.sha }}
          restore-keys: syntax-style-cache-
      
      - run: brew style ${{ github.repository }}
        continue-on-error: true

      - run: brew typecheck ${{ github.repository }}

  audit:
    name: audit
    needs: syntax
    strategy:
      fail-fast: false
      matrix:
        macos: [macos-latest, macos-13]
    runs-on: ${{ matrix.macos }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: true
          test-bot: false

      - name: Run brew readall on all casks (arm)
        if: ${{ startsWith(runner.arch, 'ARM') }}
        run: brew readall --os=all --arch=all ${{github.repository}}
      - name: Run brew readall on all casks (intel)
        if: ${{ startsWith(runner.arch, 'X') }}
        run: brew readall --os=all ${{github.repository}}

      - name: Run brew audit --skip-style on ${{github.repository}}
        run: |
          brew audit --os=all --arch=all --skip-style --except=version --tap ${{github.repository}}

      - name: Run brew audit --online on ${{github.repository}}
        run: |
          brew audit --os=all --arch=all --skip-style --except=version --online --signing --tap ${{github.repository}}
